name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: viliusddd/composite@master
        with: 
          name: OctoCat