# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: See mounted paths
        run: net use

      - name: Kill Pollinator and WebService
        run: | 
          C:\git\deadline-pipeline\pollinator\command\stop.cmd

      # - name: Deploy plugins
      #   run: | start.cmd
      #     net use W: \\10.1.1.7\DeadlineFiles /persistent:yes /savecred
      #     C:\tools\miniconda3\envs\py27_x64\python.exe deployment\deploy.py
      #   working-directory: C:\git\deadline-pipeline
      #   shell: cmd

      # - name: Start Pollinator
      #   run: |
      #     start "" start.cmd
      #   working-directory: C:\git\deadline-pipeline\pollinator\command
      #   shell: cmd

      - name: Restart Instance
        run: |
          shutdown /r
        shell: cmd
