# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run net use to see mounted paths
        run: net use

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          net use W: \\10.1.1.7\DeadlineFiles /persistent:yes /savecred
          cd C:\git\deadline-pipeline\
          C:\tools\miniconda3\envs\py27_x64\python.exe C:\git\deadline-pipeline\deployment\deploy.py
